### ISSUE TITLE
Fix weird audio bug

### ISSUE THREAD

**Issue by Square789** [Square789/PydayNightFunkin#23]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 76, in _thread_run
    self.run()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 157, in run
    player.refill(write_size)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 178, in refill
    self.write(audio_data, length)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 293, in write
    write_ptr = self._ds_buffer.lock(self._write_cursor_ring, length)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\interface.py", line 401, in lock
    self._native_buffer.Lock(write_cursor,
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\com.py", line 150, in _call
    ret = self.method.get_field()(self.i, self.name)(obj, *args)
  File "_ctypes/callproc.c", line 948, in GetResult
OSError: [WinError -2147024809] The parameter is incorrect
```
Can probably be done by creating a wrapper class around pyglet's player that takes some extra precautions when used.
*This happens sometimes when switching between the main menu and title scene

**Comment by Square789** [comment]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 76, in _thread_run
    self.run()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 157, in run
    player.refill(write_size)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 178, in refill
    self.write(audio_data, length)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 299, in write
    audio_data.consume(write_ptr.audio_length_1.value, self.source.audio_format)
ReferenceError: weakly-referenced object no longer exists
```
damnit, this one is new as well. Happened randomly while starting game scene; Probably while attempting to play either the song or the countdown sounds

**Comment by Square789** [comment]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\usr\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 76, in _thread_run
    self.run()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\mediathreads.py", line 157, in run
    player.refill(write_size)
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 173, in refill
    audio_data = self._get_audiodata()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 194, in _get_audiodata
    self._get_new_audiodata()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 202, in _get_new_audiodata
    compensation_time = self.get_audio_time_diff()
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\base.py", line 147, in get_audio_time_diff
    audio_time = self.get_time() or 0
  File "C:\Users\usr\Code\python\PydayNightFunkin\venv\lib\site-packages\pyglet\media\drivers\directsound\adaptation.py", line 321, in get_time
    result = ts + (self._play_cursor - cursor) / float(self.source.audio_format.bytes_per_second)
ReferenceError: weakly-referenced object no longer exists
```
someone is doing something very wrong
Happened on InGame scene load again

**Comment by Square789** [comment]
I believe that was all caused due to me not holding on to some sources, since songs are now cached in the asset system manager, that shouldn't happen anymore.
(Incoming fix)
